// Generated by CoffeeScript 1.4.0
var UserList, admin;

admin = admin || {};

UserList = Backbone.Collection.extend({
  model: admin.User,
  localStorage: new Backbone.LocalStorage('users-backbone'),
  nextOrder: function() {
    if (!this.length) {
      return 1;
    }
    return this.last().get('order') + 1;
  },
  comparator: function(user) {
    return user.get('first_name');
  }
});

admin.Users = new UserList();
