// Generated by CoffeeScript 1.4.0
var drivesController,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

drivesController = drivesController || {};

jQuery(function() {
  var Drive, DrivesController;
  DrivesController = (function() {

    function DrivesController() {
      this.load = __bind(this.load, this);

      this.ajax = __bind(this.ajax, this);
      this.statusMsg = $('#trips-driving-msg');
      this.statusLoader = $('#trips-driving-loader');
      setTimeout(this.ajax, 1000);
    }

    DrivesController.prototype.ajax = function() {
      var _this = this;
      $.ajax({
        url: '/trips_ajax.php',
        type: 'GET',
        data: {
          'data': JSON.stringify({})
        },
        success: this.load,
        complete: function(xhr, status) {
          if (status !== 'success') {
            return _this.statusMsg.html("<em>" + xhr.statusText + "</em>");
          }
        }
      });
      if (true) {
        return this.statusLoader.fadeOut(500, function() {
          return _this.statusMsg.fadeIn(500);
        });
      }
    };

    DrivesController.prototype.load = function(json) {
      var data;
      data = JSON.parse(json);
      return console.log(data);
    };

    return DrivesController;

  })();
  Drive = (function() {

    function Drive(data) {
      this.data = data;
    }

    return Drive;

  })();
  return drivesController = new DrivesController();
});
