// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['lib/bootstrap-datepicker', 'components/user-interface'], function(datepicker, UserInterface) {
  /*
          A Date module that uses a Bootstrap DatePicker.
  */

  var DatePicker;
  return DatePicker = (function(_super) {

    __extends(DatePicker, _super);

    function DatePicker(container, date, required) {
      this.container = container;
      this.required = required != null ? required : false;
      this.getTime = __bind(this.getTime, this);

      DatePicker.__super__.constructor.call(this, this.container);
      this.date = date.datepicker().data('datepicker');
    }

    /*
                Returns date as time in integer value, if entered
    */


    DatePicker.prototype.getTime = function() {
      var dateString;
      dateString = this.date.element.children().filter('input').val();
      if (!dateString) {
        if (this.required) {
          this.setError('Missing information.');
        }
        return null;
      }
      this.removeError();
      return this.date.date.valueOf() / 1000;
    };

    return DatePicker;

  })(UserInterface);
});
