// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['components/user-interface'], function(UserInterface) {
  var TextInput;
  return TextInput = (function(_super) {

    __extends(TextInput, _super);

    function TextInput(container, input, required) {
      this.container = container;
      this.input = input;
      this.required = required != null ? required : false;
      this.setValue = __bind(this.setValue, this);

      this.getValue = __bind(this.getValue, this);

      TextInput.__super__.constructor.call(this, this.container);
    }

    TextInput.prototype.getValue = function() {
      var inputString;
      inputString = this.input.val().trim();
      if (this.required && !inputString) {
        this.setError('Required field.');
        return null;
      }
      this.removeError();
      return inputString;
    };

    TextInput.prototype.setValue = function(val) {
      this.input.val(val);
      return this.removeError();
    };

    return TextInput;

  })(UserInterface);
});
