// Generated by CoffeeScript 1.4.0
var admin;

admin = admin || {};

admin.User = Backbone.Model.extend({
  defaults: {
    first_name: '',
    last_name: '',
    email_address: '',
    password: '',
    drivers_license_id: '',
    gender: ''
  }
});
